<?php
/**
 * Created by PhpStorm.
 * User: ThinkPad
 * Date: 2019-01-17
 * Time: 16:37
 */

namespace app\common\exception;


use Exception;
use think\exception\Handle;
use think\exception\HttpException;
use think\Response;

class Http extends Handle
{
    public function  render(Exception $e)
    {
        if($e instanceof HttpException){
            $statusCode = $e->getStatusCode ();

            if(stristr($e->getMessage(),"module not exists:")){
                return Response::create("
                <script>window.location.href='http://{$_SERVER[ 'HTTP_HOST' ]}';
                </script>", "html")->send ();
            }

        }

        return parent::render($e); // TODO: Change the autogenerated stub
    }

}